version: '2'
services:
    sampleapplication-app:
        image: sampleapplication
        external_links:
            - sampleapplication-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/sampleapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
        ports:
            - 8080:8080
    sampleapplication-mysql:
        extends:
            file: mysql.yml
            service: sampleapplication-mysql
